### ISSUE TITLE
Donation button

### ISSUE THREAD

**Issue by mcandre** [diy-ejuice/diy-flavor-safety#11]
**NOTE:** Do not open a feature request for anything related to the vendors/flavors/ingredient categorization data. For that, please create a data issue. Feel free to remove this note before submitting your issue.

## Current Behavior

Hi, I just want to express my support for this open data system to improve health and safety for millions of users. Thank you and everyone for contributing to the effort. A donation link on the home page could help go towards any maintenance costs.

## Desired Behavior

Link to a donation method from the home page.

## Proposed Solution

Patreon

**Comment by ayan4m1** [comment]
You're welcome. No plans for donations.
