### ISSUE TITLE
Flavorah Rich Cinnamon

### ISSUE THREAD

**Issue by mcandre** [diy-ejuice/diy-flavor-safety#12]
## Details

I would like to report a missing

- [x] Flavor
- [ ] Ingredient

### Flavor Info

- Vendor name (e.g. Capella): Flavorah
- Flavor name (e.g. Cool Mint): Rich Cinnamon

### Source

Describe the source of your information. Provide as much evidence as you can.

### Ingredient Info

- Chemical name(s): cinnamic aldehyde
- CAS number(s):

### Source

Provide all of your research on this ingredient. We expect to see multiple relevant scientific studies and/or corroboration from academics/toxicologists.

The manufacturer warns:

> Note: This flavor contains cinnamic aldehyde.

https://shop.flavorah.com/shop/concentrated-rich-cinnamon-flavor-2119#attr=

There are reports of this chemical disrupting lung cell function.

https://shop.flavorah.com/shop/concentrated-rich-cinnamon-flavor-2119#attr=

**Comment by ayan4m1** [comment]
No studies / corroborating evidence for cinnamic aldehyde were provided. Closing.
