### ISSUE TITLE
Reddit bot to warn for known dangerous flavors

### ISSUE THREAD

**Issue by mcandre** [diy-ejuice/diy-flavor-safety#13]
The DIY ejuice subreddit is a popular discussion board for sharing recipes. Would be helpful for newbies, if a bot would read through posts and comments.

A short warning with a link to the safety app could help to steer users away from risky ingredients.

**Comment by ayan4m1** [comment]
There would be negative backlash from users thinking that the bot is scolding them, so this is not something I'm willing to implement.
